name: isro_chronicle
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  google_fonts: ^5.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  http: ^1.1.0
  url_launcher: ^6.1.14
  flutter_staggered_grid_view: ^0.7.0
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/glogo.png
    - images/bg.jpg
    - images/ISRO.gif
    - images/launch vehicles/aslv.jpg    
    - images/launch vehicles/gslv.jpg
    - images/launch vehicles/hrlv.jpg
    - images/launch vehicles/lvm.jpg
    - images/launch vehicles/pslv.jpg
    - images/launch vehicles/slv3.jpg
    - images/launch vehicles/sslv.jpg
    - images/up/gy.png
    - images/up/gy2.jpg
    - images/up/mom.jpg
    - images/up/nisar.jpg
    - images/up/sy.jpg
    - images/up/xp.jpg
    - images/satellite.png

    
